version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Fangster123!
      MYSQL_DATABASE: myproject
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-gameproject
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/myproject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Fangster123!
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network


volumes:
  db-data:

networks:
  my-network:
